excluded:
  - Pods
  - SwifterUI/SwifterUI/UILibrary/Assets/SFAssets.swift

disabled_rules:
  - trailing_whitespace
  - trailing_newline
  - identifier_name
  - line_length

type_body_length:
  warning: 700
  error: 900

file_length:
  warning: 600
  error: 1000
