//
//  SFAssets.swift
//  SwifterUI
//
//  Created by Brandon Maldonado on 25/12/17.
//  Copyright © 2017 . All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class SFAssets : NSObject {

    //// Cache

    private struct Cache {
        static let white: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        static let black: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)
        static let separatorBlack: UIColor = UIColor(red: 0.169, green: 0.169, blue: 0.176, alpha: 1.000)
        static let separatorWhite: UIColor = UIColor(red: 0.886, green: 0.886, blue: 0.894, alpha: 1.000)
        static let alternativeWhite: UIColor = UIColor(red: 0.937, green: 0.937, blue: 0.957, alpha: 1.000)
        static let alternativeBlack: UIColor = UIColor(red: 0.100, green: 0.100, blue: 0.100, alpha: 1.000)
        static let gray: UIColor = UIColor(red: 0.941, green: 0.941, blue: 0.941, alpha: 1.000)
        static let lightGray: UIColor = UIColor(red: 0.741, green: 0.737, blue: 0.757, alpha: 1.000)
        static let darkGray: UIColor = UIColor(red: 0.557, green: 0.557, blue: 0.576, alpha: 1.000)
        static let orange: UIColor = UIColor(red: 1.000, green: 0.580, blue: 0.102, alpha: 1.000)
        static let blue: UIColor = UIColor(red: 0.000, green: 0.533, blue: 1.000, alpha: 1.000)
    }

    //// Colors

    @objc dynamic public class var white: UIColor { return Cache.white }
    @objc dynamic public class var black: UIColor { return Cache.black }
    @objc dynamic public class var separatorBlack: UIColor { return Cache.separatorBlack }
    @objc dynamic public class var separatorWhite: UIColor { return Cache.separatorWhite }
    @objc dynamic public class var alternativeWhite: UIColor { return Cache.alternativeWhite }
    @objc dynamic public class var alternativeBlack: UIColor { return Cache.alternativeBlack }
    @objc dynamic public class var gray: UIColor { return Cache.gray }
    @objc dynamic public class var lightGray: UIColor { return Cache.lightGray }
    @objc dynamic public class var darkGray: UIColor { return Cache.darkGray }
    @objc dynamic public class var orange: UIColor { return Cache.orange }
    @objc dynamic public class var blue: UIColor { return Cache.blue }

}
